import { LitElement } from 'lit';
import SlInput from '@shoelace-style/shoelace/dist/components/input/input.js';
import SlCheckbox from '@shoelace-style/shoelace/dist/components/checkbox/checkbox.js';
import SlColorPicker from '@shoelace-style/shoelace/dist/components/color-picker/color-picker.js';
import SlSelect from '@shoelace-style/shoelace/dist/components/select/select.js';
import SlTextarea from '@shoelace-style/shoelace/dist/components/textarea/textarea.js';
import type { UInputModel, UInputType, UInputSize, UInputSelectItem, UInputMeta } from './UInputModel';
export declare class UInput extends LitElement implements UInputModel {
    input: SlInput | SlCheckbox | SlColorPicker | SlSelect | SlTextarea;
    type: UInputType;
    size: UInputSize;
    disabled: boolean;
    readonly: boolean;
    filled: boolean;
    rounded: boolean;
    clearable: boolean;
    label?: string;
    help?: string;
    icon?: string;
    hint?: string;
    minLength?: number;
    maxLength?: number;
    min?: number;
    max?: number;
    autofocus: boolean;
    selectItems?: UInputSelectItem[];
    context?: any;
    path?: string;
    value?: any;
    default?: any;
    required: boolean;
    pattern?: string;
    invalidMessage?: string;
    meta?: UInputMeta;
    protected updated(changedProperties: any): Promise<void>;
    private autoBind;
    render(): import("lit").TemplateResult<1>;
    private renderCheckbox;
    private renderColorPicker;
    private renderSelect;
    private renderTextArea;
    private renderText;
    private handleChanged;
    private convertValue;
    checkValidity(): boolean;
    static styles: import("lit").CSSResult;
}
